In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
#import RandomForestRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor, BaggingRegressor, ExtraTreesRegressor

#import accuracy
from sklearn.metrics import accuracy_score, mean_squared_error, r2_score,precision_score, recall_score, f1_score
from pycaret.regression import *

In [4]:
#components
arr = ["H2S","CH4","ethyl","N2","O2","methanol","ethanol","methoxyethanol","ethoxy ethanol","1-butanol","1-pentanol","2-pentanol"]
#import dataset
df = pd.read_excel('Book.xlsx')
#define component
comp = 'H2S'
#define mole fraction
mfl = 'Yi'
df = df[df['C1'] == 'CO2']
df = df[df['C2']==comp]
df = df[df['method'] == 'exp']
#remove unnecessary features from dataset
df = df[['temp','pressure','C1','C2','Xi','Yi']]
print(df.shape)

(97, 6)

In [9]:
#import termo data for further validation
termo = pd.read_excel('Excel.xlsx',sheet_name='H2S')
termo = termo[['pressure','Xi','Yi','temp','C1','C2','Tc','Pc']].dropna(axis=0)
display(termo.head(5))

    pressure        Xi        Yi    temp   C1   C2    Tc    Pc
5    2026500  0.215426  0.532555  273.15  CO2  H2S  33.5  9.13
6    2026500  0.308493  0.620869  268.15  CO2  H2S  33.5  9.13
7    2026500  0.455658  0.710332  263.15  CO2  H2S  33.5  9.13
19   3039750  0.249500  0.523415  288.15  CO2  H2S  33.5  9.13
20   3039750  0.343402  0.607458  283.15  CO2  H2S  33.5  9.13

In [10]:
# split labels
X = df[['pressure','temp',mfl]]
y = df[mfl]
#X = pd.get_dummies(X, columns=['C1', 'C2'])
print(X.columns)
s= setup(X,target=mfl)
best = compare_models()
evaluate_model(best)
model = finalize_model(best)
predictions = predict_model(model)

# Extract y_test and y_pred from predictions
y_test = predictions[mfl].values
y_pred = df[mfl].values

# Print y_test and y_pred
print("y_test:", y_test)
print("y_pred:", y_pred)

Index(['pressure', 'temp', 'Yi'], dtype='object')

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

y_test: [8.10e+02 1.31e-01 1.22e-01 9.42e-01 5.31e-01 2.40e-01 4.55e-01 7.01e-01
 6.69e-01 5.31e-01 1.00e+00 8.10e-01 8.35e-01 3.53e-01 4.96e-01 6.62e-01
 1.00e+00 6.14e-01 8.62e-01 3.50e-02 8.99e-01 2.71e-01 0.00e+00 9.69e-01
 3.38e-01 1.00e+00 4.23e-01 7.85e+02 5.44e-01 6.87e-01]
y_pred: [0.00e+00 1.31e-01 2.40e-01 3.41e-01 4.41e-01 5.31e-01 6.65e-01 7.15e+02
 7.85e+02 8.10e+02 8.40e+02 8.89e+02 1.00e+00 0.00e+00 5.60e-01 1.69e-01
 2.61e-01 3.53e-01 4.55e-01 5.31e-01 6.11e-01 6.98e-01 8.08e-01 8.37e-01
 8.66e-01 1.00e+00 0.00e+00 1.24e-01 2.16e-01 3.00e-01 3.82e-01 4.67e-01
 5.46e-01 6.30e-01 7.20e-01 8.35e-01 8.62e-01 8.99e-01 9.42e-01 1.00e+00
 0.00e+00 4.50e-02 1.32e-01 2.16e-01 2.95e-01 3.74e-01 4.55e-01 5.34e-01
 6.14e-01 7.01e-01 8.11e-01 9.08e-01 9.50e-01 1.00e+00 0.00e+00 3.50e-02
 1.22e-01 1.94e-01 2.71e-01 3.45e-01 4.23e-01 4.96e-01 5.83e-01 6.62e-01
 7.59e-01 9.01e-01 9.38e-01 1.00e+00 0.00e+00 9.00e-02 1.60e-01 2.26e-01
 3.00e-01 3.69e-01 4.42e-01 5.32e-01 6.01e-01 6.87e-01 7.96e-01 9.69e-01
 1.00e+00 0.00e+00 5.00e-02 1.27e-01 1.76e-01 2.40e-01 3.08e-01 3.73e-01
 4.38e-01 5.08e-01 5.44e-01 0.00e+00 3.38e-01 5.31e-01 6.69e-01 8.10e-01
 1.00e+00]

In [14]:
predictions.iloc[1:7]

     pressure        temp     Yi  prediction_label
339   2.02650  293.149994  0.131          0.150788
394   6.08000  343.149994  0.122          0.128761
376   4.05300  279.149994  0.942          0.936214
431   2.02700  273.149994  0.531          0.558834
340   2.02650  288.149994  0.240          0.243107
356   3.03975  293.149994  0.455          0.472899

In [12]:
predictions.to_csv(f"{comp}{mfl}.csv",index=False)